name: units
parameters: |
  __spring.xml=xharbor/xharbor.xml
children:
  - name: opentracing
    parameters: |
      endpoint=XXXX
      username=XXXX
      password=XXXX
  - name: nettystats
  - name: redisclient
    parameters: |
      redis.server.hostname=localhost
      redis.server.passwd=passwd
      redis.server.dbno=255
  - name: conf
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 8083
  - name: nop.httpout
    children:
      - name: httpfeatures.compress
        parameters: |
          features.name=compress
        children:
          - name: feature_compress
          - name: feature_logging
      - name: httpfeatures.default
        parameters: |
          features.name=default
#        children:
#          - name: feature_logging
  - name: trade_schd.default
    parameters: |
      worker.count = 4
  - name: httpclient.default
    parameters: |
      http.client.thread.count = 2
      http.client.inbound.blocksize = 16384
      http.client.inbound.recvbuf = 16384
      http.client.outbound.sendbuf = 16384
      http.client.outbound.lowmark = 4096
      http.client.outbound.highmark = 16384
    children:
      - name: httpclient_dashboard
  - name: rules.console-auths
    parameters: name=console-auths
    children:
      - name: auth.jmxhtml
        parameters: |
          auth.headers=x-jmx,jmxhtml(\\w)*
          auth.user=test
          auth.password=test
  - name: router.console
    children:
      - name: rules.console-rwreqs
        parameters: priority=100
        children:
          - name: rwreq.jmxhtml
            parameters: |
              rewrite.path=/jmxhtml/
              rewrite.to=/
              rewrite.header.name=x-jmx
              rewrite.header.value=jmxhtml.self
          - name: rwreq.hystrix
            parameters: |
              rewrite.path=/hystrix/
              rewrite.to=/
              rewrite.header.name=x-hystrix
              rewrite.header.value=hystrix
      - name: fwds.console-100
        parameters: priority=70
        children:
          - name: forward.jmxhtml.self
            parameters: |
              forward.headers=x-jmx,jmxhtml.self
              forward.to=http://127.0.0.1:8083
          - name: forward.hystrix.self
            parameters: |
              forward.headers=x-hystrix,hystrix
              forward.to=http://127.0.0.1:4004
      - name: httpserver.console
        parameters: |
          http.server.inbound.blocksize = 8192
          http.server.inbound.recvbuf = 8192
        children:
          - name: httpin.8889
            parameters: |
              http.port=8889
              tracing.enabled = false
            children:
              - name: feature_logging
  - name: httpserver
    parameters: |
      http.server.inbound.recvbuf = 8192
      http.server.work.thread.count=1
    children:
      - name: restin.4004
        parameters: |
          http.port = 4004
          http.address=0.0.0.0
          restin.pathpattern=/hystrix.stream|/mock
          restin.category = none
  - name: hystrixstream
  - name: mockctrl
    parameters: |
      timeout = 29000
  